Issues #6, #27, #32 and part of #28
MarketDiscord/E-Bot pull request #34
Opened 2023-01-29 15:58 UTC by AsarixLeDev

2023-01-29 16:02 UTC, Deo-Favente commented
L'issue #27 est aussi fix dans cette issue.

2023-01-29 16:04 UTC, Deo-Favente commented on config.py
> +    if not os.path.exists(CONFIG_DIR):
Ce check est un peu redondant vu que déjà fait dans create_file

2023-01-29 16:04 UTC, Deo-Favente commented on config.py
> +    config_path = create_file(CONFIG_FILE_NAME, json_default={"TOKEN": ""})
Bien, il faudra ajouter mon path "DEV_MODE" si ma PR est acceptée

2023-01-29 16:09 UTC, Deo-Favente requested changes

2023-01-29 16:09 UTC, Deo-Favente commented on config.py
> +def db_file_path():
Méthode à retirer car pas utilisée ni nécéssaire

2023-01-29 16:10 UTC, AsarixLeDev commented on config.py
> +def db_file_path():
Tu peux faire des sudokus si tu t'ennuies

2023-01-29 16:14 UTC, Deo-Favente commented on config.py
> +def db_file_path():
Je préférerais que tu touches pas a ma DB tant qu'elle fonctionne correctement

2023-01-31 17:47 UTC, AsarixLeDev commented
Issue #30 fixed too there

2023-01-31 18:44 UTC, Deo-Favente commented
@AsarixLeDev je te relance parce que je ne peux pas ajouter de commit à ta PR, merci de supprimer la méthode demandée pour que j'accepte le merge.

2023-01-31 18:46 UTC, AsarixLeDev commented
> @AsarixLeDev je te relance parce que je ne peux pas ajouter de commit à ta PR, merci de supprimer la méthode demandée pour que j'accepte le merge.

Ou est l'alternative ? Dans le database.py ?

2023-01-31 18:52 UTC, Deo-Favente commented
> > @AsarixLeDev je te relance parce que je ne peux pas ajouter de commit à ta PR, merci de supprimer la méthode demandée pour que j'accepte le merge.
> 
> Ou est l'alternative ? Dans le database.py ?

Il n'y a pas d'alternative parce qu'on ne fetch pas le path de la DB, qui n'est pas censée quitter le dossier resources. Sauf si tu me donne un cas concret de là ou ta méthode peut être utile, elle ressemble juste à un résidus d'un système qu'on utilise plus pour le moment

2023-01-31 19:17 UTC, Deo-Favente approved these changes

2023-01-31 19:17 UTC, merged